#!/usr/bin/env python

import sys

from pyaml_processor import pyaml_file


def main():
    reformat = False
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <YAML file>")
        exit(1)

    if sys.argv[1] == "-r":
        reformat = True
        sys.argv.pop(1)

    (lines, error) = pyaml_file(sys.argv[1], reformat)
    print(lines)
    exit(-1 if error else 0)


if __name__ == "__main__":
    main()
